table.insert(_defaultJobData, {
	Type = "Government",
	LastUpdated = 1689602424,
	Id = "police",
	Name = "Police",
	Salary = 1200,
	SalaryTier = 1,
	Workplaces = {
		{
			Id = "lspd",
			Name = "Los Santos Police Department",
			Grades = {
				{
					Id = "chief",
					Name = "Chief",
					Level = 99,
					Permissions = {
						JOB_STORAGE = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						PD_MANAGE_TRIALS = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						ems_alerts = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_FIRE = true,
						BANK_ACCOUNT_MANAGE = true,
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						impound = true,
						MDT_PROMOTE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_HIRE = true,
						PD_SECURED_ARMORY = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						TABLET_TWEET = true,
						FLEET_VEHICLES_3 = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						FLEET_VEHICLES_0 = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_4 = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
				{
					Id = "achief",
					Name = "Assistant Chief",
					Level = 90,
					Permissions = {
						JOB_STORAGE = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						PD_MANAGE_TRIALS = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_FIRE = true,
						MDT_HIRE = true,
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						impound = true,
						MDT_PROMOTE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						BANK_ACCOUNT_MANAGE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						PD_SECURED_ARMORY = true,
						FLEET_VEHICLES_0 = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_4 = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
				{
					Id = "captain",
					Name = "Captain",
					Level = 70,
					Permissions = {
						MDT_INCIDENT_REPORT_CREATE = true,
						BANK_ACCOUNT_BALANCE = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						impound_police = true,
						PD_SECURED_ARMORY = true,
						PD_COMMAND = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						ems_alerts = true,
						FLEET_VEHICLES_0 = true,
						BANK_ACCOUNT_DEPOSIT = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_HIGH_COMMAND = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_PROMOTE = true,
						MDT_HIRE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						PD_RAID = true,
						PD_MANAGE_TRIALS = true,
						police_alerts = true,
						USE_PD_TAGS = true,
						FLEET_VEHICLES_1 = true,
						FLEET_MANAGEMENT = true,
						JOB_STORAGE = true,
						FLEET_VEHICLES_4 = true,
						impound = true,
						MDT_FIRE = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 60,
					Permissions = {
						FLEET_MANAGEMENT = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_HIRE = true,
						FLEET_VEHICLES_3 = true,
						PD_RAID = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_COMMAND = true,
						impound_police = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						PD_MANAGE_TRIALS = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						impound = true,
						JOB_STORAGE = true,
						MDT_PROMOTE = true,
						PD_SECURED_ARMORY = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_FIRE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_HIGH_COMMAND = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 50,
					Permissions = {
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						PD_RAID = true,
						impound_police = true,
						PD_COMMAND = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						JOB_STORAGE = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						FLEET_VEHICLES_1 = true,
						impound = true,
						FLEET_VEHICLES_3 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_4 = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						PD_SECURED_ARMORY = true,
					},
				},
				{
					Id = "corporal",
					Name = "Corporal",
					Level = 20,
					Permissions = {
						MDT_EDIT_EMPLOYEE = true,
						ems_alerts = true,
						PD_COMMAND = true,
						USE_PD_TAGS = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						PD_SECURED_ARMORY = true,
						impound_police = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						police_alerts = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						impound = true,
						FLEET_VEHICLES_1 = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
					},
				},
				{
					Id = "sofficer",
					Name = "Senior Officer",
					Level = 15,
					Permissions = {
						MDT_INCIDENT_REPORT_CREATE = true,
						JOB_STORAGE = true,
						police_alerts = true,
						impound_police = true,
						impound = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_SECURED_ARMORY = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_1 = true,
						USE_PD_TAGS = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
					},
				},
				{
					Id = "officer",
					Name = "Officer",
					Level = 10,
					Permissions = {
						JOB_STORAGE = true,
						impound_police = true,
						FLEET_VEHICLES_1 = true,
						impound = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						PD_SECURED_ARMORY = true,
						police_alerts = true,
						MDT_POLICE_FTO_REPORTS = true,
						ems_alerts = true,
						USE_PD_TAGS = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
					},
				},
				{
					Id = "pofficer",
					Name = "Probationary Officer",
					Level = 2,
					Permissions = {
						JOB_STORAGE = true,
						PD_SECURED_ARMORY = true,
						impound_police = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						USE_PD_TAGS = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						police_alerts = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						impound = true,
						ems_alerts = true,
						FLEET_VEHICLES_0 = true,
						PD_SECURED_ARMORY = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
			},
		},
		{
			Id = "bcso",
			Name = "Blaine County Sheriff's Office",
			Grades = {
				{
					Id = "sheriff",
					Name = "Sheriff",
					Level = 99,
					Permissions = {
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_1 = true,
						BANK_ACCOUNT_BALANCE = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						TABLET_TWEET = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						impound_police = true,
						impound = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						MDT_EDIT_EMPLOYEE = true,
						PD_SECURED_ARMORY = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_PROMOTE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						PD_RAID = true,
						FLEET_VEHICLES_2 = true,
						JOB_STORAGE = true,
						MDT_HIRE = true,
						PD_MANAGE_TRIALS = true,
						BANK_ACCOUNT_MANAGE = true,
						police_alerts = true,
						FLEET_VEHICLES_3 = true,
						BANK_ACCOUNT_BILL = true,
						PD_HIGH_COMMAND = true,
						FLEET_VEHICLES_4 = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_POLICE_FTO_REPORTS = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_WITHDRAW = true,
						FLEET_VEHICLES_0 = true,
						MDT_FIRE = true,
					},
				},
				{
					Id = "usheriff",
					Name = "Undersheriff",
					Level = 90,
					Permissions = {
						JOB_STORAGE = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						BANK_ACCOUNT_BILL = true,
						MDT_FIRE = true,
						PD_COMMAND = true,
						PD_SECURED_ARMORY = true,
						impound_police = true,
						PD_MANAGE_TRIALS = true,
						FLEET_VEHICLES_2 = true,
						ems_alerts = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						BANK_ACCOUNT_MANAGE = true,
						police_alerts = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_RAID = true,
						FLEET_VEHICLES_4 = true,
						FLEET_VEHICLES_3 = true,
						PD_HIGH_COMMAND = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_HIRE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_PROMOTE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						FLEET_MANAGEMENT = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						FLEET_VEHICLES_0 = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_BALANCE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
					},
				},
				{
					Id = "captain",
					Name = "Captain",
					Level = 70,
					Permissions = {
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_MANAGE_TRIALS = true,
						impound = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						police_alerts = true,
						MDT_PROMOTE = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_HIRE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_FIRE = true,
						PD_SECURED_ARMORY = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 60,
					Permissions = {
						BANK_ACCOUNT_DEPOSIT = true,
						ems_alerts = true,
						PD_COMMAND = true,
						USE_PD_TAGS = true,
						impound_police = true,
						FLEET_VEHICLES_4 = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						PD_SECURED_ARMORY = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_RAID = true,
						FLEET_MANAGEMENT = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						police_alerts = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						FLEET_VEHICLES_0 = true,
						MDT_HIRE = true,
						impound = true,
						MDT_FIRE = true,
						PD_HIGH_COMMAND = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_1 = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						FLEET_VEHICLES_2 = true,
						PD_MANAGE_TRIALS = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 50,
					Permissions = {
						PD_COMMAND = true,
						USE_PD_TAGS = true,
						FLEET_VEHICLES_4 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_SECURED_ARMORY = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						impound_police = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_HIRE = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						ems_alerts = true,
						MDT_EDIT_EMPLOYEE = true,
						impound = true,
						PD_MANAGE_TRIALS = true,
						police_alerts = true,
						FLEET_VEHICLES_3 = true,
						PD_RAID = true,
					},
				},
				{
					Id = "corporal",
					Name = "Corporal",
					Level = 20,
					Permissions = {
						ems_alerts = true,
						USE_PD_TAGS = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						PD_SECURED_ARMORY = true,
						impound_police = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						police_alerts = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						impound = true,
					},
				},
				{
					Id = "sdeputy",
					Name = "Senior Deputy",
					Level = 15,
					Permissions = {
						police_alerts = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						FLEET_VEHICLES_1 = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						PD_SECURED_ARMORY = true,
						impound_police = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						JOB_STORAGE = true,
						ems_alerts = true,
						USE_PD_TAGS = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
					},
				},
				{
					Id = "deputy",
					Name = "Deputy",
					Level = 10,
					Permissions = {
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						PD_SECURED_ARMORY = true,
						impound_police = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						police_alerts = true,
					},
				},
				{
					Id = "pdeputy",
					Name = "Probationary Deputy",
					Level = 2,
					Permissions = {
						JOB_STORAGE = true,
						ems_alerts = true,
						impound_police = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						police_alerts = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						impound = true,
						ems_alerts = true,
						FLEET_VEHICLES_0 = true,
						PD_SECURED_ARMORY = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
			},
		},
		{
			Id = "sast",
			Name = "San Andreas State Troopers",
			Grades = {
				{
					Id = "commissioner",
					Name = "Commissioner",
					Level = 99,
					Permissions = {
						FLEET_VEHICLES_3 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_BALANCE = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_RAID = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						BANK_ACCOUNT_BILL = true,
						JOB_STORAGE = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						FLEET_VEHICLES_1 = true,
						TABLET_TWEET = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						impound = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_FIRE = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_0 = true,
						MDT_PROMOTE = true,
						FLEET_VEHICLES_4 = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						impound_police = true,
						PD_MANAGE_TRIALS = true,
						ems_alerts = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						PD_SECURED_ARMORY = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
					},
				},
				{
					Id = "colonel",
					Name = "Colonel",
					Level = 99,
					Permissions = {
						FLEET_VEHICLES_3 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_BALANCE = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_RAID = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						BANK_ACCOUNT_BILL = true,
						JOB_STORAGE = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						FLEET_VEHICLES_1 = true,
						TABLET_TWEET = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						impound = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_FIRE = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_0 = true,
						MDT_PROMOTE = true,
						FLEET_VEHICLES_4 = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						impound_police = true,
						PD_MANAGE_TRIALS = true,
						ems_alerts = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						PD_SECURED_ARMORY = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
					},
				},
				{
					Id = "major",
					Name = "Major",
					Level = 90,
					Permissions = {
						JOB_STORAGE = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						PD_MANAGE_TRIALS = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_FIRE = true,
						MDT_HIRE = true,
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						impound = true,
						MDT_PROMOTE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						BANK_ACCOUNT_MANAGE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						PD_SECURED_ARMORY = true,
						FLEET_VEHICLES_0 = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_4 = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
				{
					Id = "captain",
					Name = "Captain",
					Level = 70,
					Permissions = {
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_MANAGE_TRIALS = true,
						impound = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						police_alerts = true,
						MDT_PROMOTE = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_HIRE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_FIRE = true,
						PD_SECURED_ARMORY = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 60,
					Permissions = {
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_MANAGE_TRIALS = true,
						impound = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						police_alerts = true,
						MDT_PROMOTE = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_HIRE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_FIRE = true,
						PD_SECURED_ARMORY = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 50,
					Permissions = {
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_EDIT_EMPLOYEE = true,
						PD_COMMAND = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_SECURED_ARMORY = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						PD_RAID = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						police_alerts = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						impound_police = true,
						FLEET_VEHICLES_1 = true,
						impound = true,
						FLEET_VEHICLES_3 = true,
						MDT_PROMOTE = true,
						MDT_FIRE = true,
						MDT_HIRE = true,
						FLEET_VEHICLES_2 = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
					},
				},
				{
					Id = "corporal",
					Name = "Corporal",
					Level = 20,
					Permissions = {
						MDT_INCIDENT_REPORT_CREATE = true,
						impound_police = true,
						USE_PD_TAGS = true,
						FLEET_VEHICLES_0 = true,
						police_alerts = true,
						impound = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						ems_alerts = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						PD_SECURED_ARMORY = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_POLICE_FTO_REPORTS = true,
					},
				},
				{
					Id = "strooper",
					Name = "Senior Trooper",
					Level = 15,
					Permissions = {
						JOB_STORAGE = true,
						PD_SECURED_ARMORY = true,
						USE_PD_TAGS = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						impound_police = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_POLICE_FTO_REPORTS = true,
					},
				},
				{
					Id = "trooper",
					Name = "Trooper",
					Level = 10,
					Permissions = {
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						FLEET_VEHICLES_0 = true,
						ems_alerts = true,
						MDT_POLICE_FTO_REPORTS = true,
						impound_police = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						police_alerts = true,
						PD_SECURED_ARMORY = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
				{
					Id = "ptrooper",
					Name = "Probationary Trooper",
					Level = 2,
					Permissions = {
						JOB_STORAGE = true,
						PD_SECURED_ARMORY = true,
						USE_PD_TAGS = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						impound_police = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						JOB_STORAGE = true,
						ems_alerts = true,
						USE_PD_TAGS = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						PD_SECURED_ARMORY = true,
					},
				},
			},
		},
		{
			Id = "guardius",
			Name = "Guardius Police Department",
			Grades = {
				{
					Id = "director",
					Name = "Director",
					Level = 99,
					Permissions = {
						FLEET_VEHICLES_3 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_BALANCE = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_RAID = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						BANK_ACCOUNT_BILL = true,
						JOB_STORAGE = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						FLEET_VEHICLES_1 = true,
						TABLET_TWEET = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						impound = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_POLICE_FTO_REPORTS = true,
						MDT_FIRE = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_0 = true,
						MDT_PROMOTE = true,
						FLEET_VEHICLES_4 = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						impound_police = true,
						PD_MANAGE_TRIALS = true,
						ems_alerts = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						PD_SECURED_ARMORY = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
					},
				},
				{
					Id = "ddirector",
					Name = "Dep. Director",
					Level = 90,
					Permissions = {
						JOB_STORAGE = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						PD_MANAGE_TRIALS = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						police_alerts = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						BANK_ACCOUNT_WITHDRAW = true,
						MDT_FIRE = true,
						MDT_HIRE = true,
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						impound = true,
						MDT_PROMOTE = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						BANK_ACCOUNT_MANAGE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						ATTORNEY_PENDING_EVIDENCE = true,
						PD_SECURED_ARMORY = true,
						FLEET_VEHICLES_0 = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_4 = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
				{
					Id = "snrcommander",
					Name = "Senior Commander",
					Level = 70,
					Permissions = {
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_MANAGE_TRIALS = true,
						impound = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						police_alerts = true,
						MDT_PROMOTE = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_HIRE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_FIRE = true,
						PD_SECURED_ARMORY = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
					},
				},
				{
					Id = "commander",
					Name = "Commander",
					Level = 60,
					Permissions = {
						FLEET_MANAGEMENT = true,
						PD_COMMAND = true,
						impound_police = true,
						FLEET_VEHICLES_2 = true,
						USE_PD_TAGS = true,
						BANK_ACCOUNT_DEPOSIT = true,
						PD_MANAGE_TRIALS = true,
						impound = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						police_alerts = true,
						MDT_PROMOTE = true,
						BANK_ACCOUNT_BALANCE = true,
						PD_HIGH_COMMAND = true,
						PD_RAID = true,
						FLEET_VEHICLES_1 = true,
						JOB_STORAGE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_HIRE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						FLEET_VEHICLES_3 = true,
						ems_alerts = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_FIRE = true,
						PD_SECURED_ARMORY = true,
						MDT_EDIT_EMPLOYEE = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
					},
				},
				{
					Id = "seniorspecialagent",
					Name = "Senior Special Agent",
					Level = 50,
					Permissions = {
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_EDIT_EMPLOYEE = true,
						PD_COMMAND = true,
						MDT_POLICE_FTO_REPORTS = true,
						PD_SECURED_ARMORY = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						PD_RAID = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_4 = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						police_alerts = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						impound_police = true,
						FLEET_VEHICLES_1 = true,
						impound = true,
						FLEET_VEHICLES_3 = true,
						MDT_PROMOTE = true,
						MDT_FIRE = true,
						MDT_HIRE = true,
						FLEET_VEHICLES_2 = true,
						JOB_STORAGE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
					},
				},
				{
					Id = "specialagent",
					Name = "Special Agent",
					Level = 15,
					Permissions = {
						JOB_STORAGE = true,
						PD_SECURED_ARMORY = true,
						USE_PD_TAGS = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						FLEET_VEHICLES_1 = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						impound_police = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_POLICE_FTO_REPORTS = true,
					},
				},
				{
					Id = "agent",
					Name = "Agent",
					Level = 10,
					Permissions = {
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						FLEET_VEHICLES_0 = true,
						ems_alerts = true,
						MDT_POLICE_FTO_REPORTS = true,
						impound_police = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						USE_PD_TAGS = true,
						police_alerts = true,
						PD_SECURED_ARMORY = true,
						MDT_INCIDENT_REPORT_CREATE = true,
					},
				},
				{
					Id = "pagent",
					Name = "Probationary Agent",
					Level = 2,
					Permissions = {
						JOB_STORAGE = true,
						PD_SECURED_ARMORY = true,
						USE_PD_TAGS = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						ems_alerts = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						impound_police = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						JOB_STORAGE = true,
						ems_alerts = true,
						USE_PD_TAGS = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						FLEET_VEHICLES_0 = true,
						impound = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INVESTIGATIVE_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						police_alerts = true,
						MDT_INVESTIGATIVE_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						PD_SECURED_ARMORY = true,
					},
				},
			},
		},
	},
})
