table.insert(_defaultJobData, {
	Type = "Government",
	LastUpdated = 1689601637,
	Id = "prison",
	Name = "Bolingbroke State Penitentiary",
	Salary = 1200,
	SalaryTier = 1,
	Workplaces = {
		{
			Id = "corrections",
			Name = "Department of Corrections",
			Grades = {
				{
					Id = "warden",
					Name = "Warden",
					Level = 10,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_MANAGEMENT = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						JOB_STORAGE = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
						TABLET_TWEET = true,
						DOC_REDUCTION = true,
						DOC_DOCUMENTS_VIEW = true,
						DOC_DOCUMENTS_CREATE = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
						DOC_HIGH_COMMAND = true,
					},
				},
				{
					Id = "dwarden",
					Name = "Deputy Warden",
					Level = 5,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						JOB_STORAGE = true,
						DOC_REDUCTION = true,
						DOC_DOCUMENTS_VIEW = true,
						DOC_DOCUMENTS_CREATE = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
						DOC_HIGH_COMMAND = true,
					},
				},
				{
					Id = "Captain",
					Name = "Captain",
					Level = 3,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						JOB_STORAGE = true,
						DOC_REDUCTION = true,
						DOC_DOCUMENTS_VIEW = true,
						DOC_DOCUMENTS_CREATE = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
						DOC_HIGH_COMMAND = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 2,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						JOB_STORAGE = true,
						DOC_REDUCTION = true,
						DOC_DOCUMENTS_VIEW = true,
						DOC_DOCUMENTS_CREATE = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 2,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						JOB_STORAGE = true,
						DOC_REDUCTION = true,
						DOC_DOCUMENTS_VIEW = true,
						DOC_DOCUMENTS_CREATE = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
					},
				},
				{
					Id = "srco",
					Name = "Senior Corrections Officer",
					Level = 2,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						JOB_STORAGE = true,
						DOC_REDUCTION = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
					},
				},
				{
					Id = "co",
					Name = "Corrections Officer",
					Level = 2,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						JOB_STORAGE = true,
						DOC_REDUCTION = true,
						DOC_REPORTS_CREATE = true,
						DOC_REPORTS_VIEW = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
					},
				},
			},
		},
	},
})
