_itemsSource["food_ingredients"] = {
	{
		name = "tomato",
		label = "Tomato",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "raspberry",
		label = "Raspberry",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "potato",
		label = "Potato",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "orange",
		label = "Orange",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "lettuce",
		label = "Lettuce",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "cucumber",
		label = "Cucumber",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "peas",
		label = "Peas",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "pickle",
		label = "Pickle",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "pineapple",
		label = "Pineapple",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "chicken",
		label = "Chicken",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "beef",
		label = "Beef",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "pork",
		label = "Pork",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "venison",
		label = "Venison",
		price = 40,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "rabbit",
		label = "Rabbit",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "unk_meat",
		label = "Meat",
		price = 20,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "dough",
		label = "Dough",
		price = 3,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "loaf",
		label = "Bread Loaf",
		price = 4,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "icing",
		label = "Icing",
		price = 3,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "sugar",
		label = "Bag of Sugar",
		price = 2,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "flour",
		label = "Bag of Flour",
		price = 2,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "rice",
		label = "Bag of Rice",
		price = 5,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "milk_can",
		label = "Milk Canister",
		price = 4,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "keg",
		label = "Keg of Irish Stout",
		description = "McDougle's Irish Stout™",
		price = 150,
		isUsable = false,
		isRemoved = false,
		isStackable = 5,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 1.5,
	},
	{
		name = "coconut_milk",
		label = "Coconut Milk",
		price = 3,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "cheese",
		label = "Bag of Cheese",
		price = 4,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "tea_leaf",
		label = "Tea Leaf",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "plastic_cup",
		label = "Plastic Cup",
		price = 5,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "coffee_beans",
		label = "Coffee Beans",
		price = 7,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "jaeger",
		label = "Jägermeister",
		price = 150,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "raspberry_liqueur",
		label = "Raspberry Liqueur",
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 30,
		type = 4,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "sparkling_wine",
		label = "Sparkling Wine",
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 30,
		type = 4,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "peach_juice",
		label = "Peach Juice",
		price = 2,
		isUsable = true,
		isRemoved = true,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "eggs",
		label = "Eggs",
		price = 2,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "yeast",
		label = "Yeast",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "grain",
		label = "Grain",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "hobs",
		label = "Hobs",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "ginger",
		label = "Ginger",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "hotdog_single",
		label = "Hotdog Single",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "popcorn_kernal",
		label = "Popcorn Kernal",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "popcorn_bucket",
		label = "Empty Bucket",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
}
