_itemsSource["rustybrowns"] = {
	-- donuts
	{
		name = "rusty_strawsprinkle",
		label = "Cherry Pop",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_strawsprinkle",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		energyModifier = {
			modifier = 1.1,
			duration = 18, -- not seconds?
			cooldown = 80, -- seconds
			skipScreenEffects = true,
		},
	},
	{
		name = "rusty_ring",
		label = "Rusty Ring",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
			Ignore = {
				PLAYER_STRESS = 10,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_ring",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		healthModifier = 12,
	},
	{
		name = "rusty_lemon",
		label = "Bannana Deep",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
			Remove = {
				PLAYER_THIRST = 3,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_lemon",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		healthModifier = 12,
	},
	{
		name = "rusty_custard",
		label = "Creampie",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
			Ignore = {
				PLAYER_STRESS = 10,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_custard",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		energyModifier = {
			modifier = 1.1,
			duration = 18, -- not seconds?
			cooldown = 80, -- seconds
			skipScreenEffects = true,
		},
	},
	{
		name = "rusty_cookiecream",
		label = "Manure Mix",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
			Remove = {
				PLAYER_THIRST = 3,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_cookiecream",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		healthModifier = 12,
	},
	{
		name = "rusty_chocstuff",
		label = "Brown Mess",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
			Remove = {
				PLAYER_THIRST = 3,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_chocstuff",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		healthModifier = 12,
	},
	{
		name = "rusty_chocsprinkle",
		label = "Chocolate Whammy",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
			Remove = {
				PLAYER_THIRST = 3,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_chocsprinkle",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		energyModifier = {
			modifier = 1.1,
			duration = 18, -- not seconds?
			cooldown = 80, -- seconds
			skipScreenEffects = true,
		},
	},
	{
		name = "rusty_blueice",
		label = "Follemos",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 45,
			},
		},
		stressTicks = { "1", "1", "1", "1", "3" },
		animConfig = {
			anim = "rusty_blueice",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		healthModifier = 12,
	},
	-- boxes
	{
		name = "rusty_strawsprinkbox",
		label = "Box of Swifty Sprinkles",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 10),
		animConfig = {
			time = 2000,
			pbConfig = {
				label = "Unpacking",
				useWhileDead = false,
				canCancel = false,
				vehicle = false,
				disarm = false,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = false,
			},
		},
	},
	{
		name = "rusty_ringmixbox",
		label = "Box of Mixed Rings",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 10),
		animConfig = {
			time = 2000,
			pbConfig = {
				label = "Unpacking",
				useWhileDead = false,
				canCancel = false,
				vehicle = false,
				disarm = false,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = false,
			},
		},
	},
	{
		name = "rusty_ringbox",
		label = "Box of Rings",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 10),
		animConfig = {
			time = 2000,
			pbConfig = {
				label = "Unpacking",
				useWhileDead = false,
				canCancel = false,
				vehicle = false,
				disarm = false,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = false,
			},
		},
	},
	{
		name = "rusty_pd",
		label = "Rusty's Sword",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 10),
		animConfig = {
			time = 2000,
			pbConfig = {
				label = "Unpacking",
				useWhileDead = false,
				canCancel = false,
				vehicle = false,
				disarm = false,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = false,
			},
		},
	},

	-- drinks
	{
		name = "shmilk",
		label = "Shmilk",
		price = 75,
		isUsable = true,
		isRemoved = true,
		isStackable = 25,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 1.00,
		durability = (60 * 60 * 24 * 3),
		statusChange = {
			Add = {
				PLAYER_THIRST = 40,
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "shmilk",
			time = 8000,
			pbConfig = {
				label = "I Need Some Shmilk",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		healthModifier = 10,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "chai_latte",
		label = "Chai Latte",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Coffee",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 15,
			},
		},
		progressModifier = {
			modifier = 40,
			min = 6,
			max = 10,
		},
	},
	{
		name = "tommy_tea",
		label = "Tommy Tea",
		price = 125,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee_expresso",
			time = 7500,
			pbConfig = {
				label = "Drinking Tea",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 100,
			},
		},
		progressModifier = {
			modifier = 60,
			min = 2,
			max = 4,
		},
	},
	{
		name = "rusty_empty",
		label = "Empty Donut Box",
		price = 5,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.0,
		isDestroyed = true,
	},
}
