_itemsSource["taco"] = {
	{
		name = "jugo",
		label = "Jugo Fruit Punch",
		description = "Definitely organic.",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_THIRST = 15,
			},
			Remove = {
				PLAYER_HUNGER = 3,
			},
		},
		animConfig = {
			anim = "soda",
			time = 15000,
			pbConfig = {
				label = "Drinking",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 2),
	},
	{
		name = "taco_soda",
		label = "Southside Soda",
		description = "Yeah, tastes about right.",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_THIRST = 15,
			},
			Remove = {
				PLAYER_HUNGER = 3,
			},
		},
		animConfig = {
			anim = "soda",
			time = 15000,
			pbConfig = {
				label = "Drinking",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 2),
	},
	{
		name = "beef_taco",
		label = "Beef Taco",
		description = "In case you don't have beef yet.",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "taco",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "tostada",
		label = "Tostada",
		description = "Deep fried or toasted?",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "taco",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{

		name = "quesadilla",
		label = "Quesadilla",
		description = "Basically grilled cheese",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "taco",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "burrito",
		label = "Burrito",
		description = "Burritoe, get it?",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "taco",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "enchilada",
		label = "Enchilada",
		description = "Meat birthday cakes.",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "taco",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "carne_asada",
		label = "Carne Asada",
		description = "Kanye Asada",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "taco",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "torta",
		label = "Torta",
		description = "Fancy sub",
		price = 1,
		isUsable = false,
		isRemoved = true,
		isStackable = 15,
		type = 6,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 15,
			},
		},
		animConfig = {
			anim = "sandwich",
			time = 8000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},

	-- Ingredients

	{
		name = "taco_chicken",
		label = "Raw Chicken Strips",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "taco_steak",
		label = "Raw Steak Strips",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "taco_beef",
		label = "Raw Ground Beef",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "taco_cheese",
		label = "Shredded Cheese",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "taco_tortilla",
		label = "Tortilla Shell",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "torta_roll",
		label = "Torta Roll",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
	{
		name = "taco_plastic_cups",
		label = "Taco Plastic Cups",
		iconOverride = "plastic_cup",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.0,
	},
}
