_bobcatWeapons = {
	`WEAPON_APPISTOL`,
	`WEAPON_MG`,
	`WEAPON_COMBATMG`,
	`WEAPON_ASSAULTRIFLE`,
	`WEAPON_COMPACTRIFLE`,
	`WEAPON_SMG`,
	`WEAPON_ASSAULTSHOTGUN`,
	`WEAPON_SAWNOFFSHOTGUN`,

	--`WEAPON_PUMPSHOTGUN`,
}
