_itemsSource["schematics_base"] = {
	{
		name = "schematic_grapple_gun",
		label = "Schematic: Grapple Gun",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'grapple',
	},
	{
		name = "schematic_pistol_ammo",
		label = "Schematic: Pistol Ammo",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'pistol_ammo',
	},
	{
		name = "schematic_smg_ammo",
		label = "Schematic: SMG Ammo",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'smg_ammo',
	},
	{
		name = "schematic_shotgun_ammo",
		label = "Schematic: Shotgun Ammo",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'shotgun_ammo',
	},
	{
		name = "schematic_thermite",
		label = "Schematic: Thermite",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'thermite',
	},
	{
		name = "schematic_blindfold",
		label = "Schematic: Blindfold",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'blindfold',
	},
	{
		name = "schematic_green_laptop",
		label = "Schematic: Green Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'green_laptop',
	},
	{
		name = "schematic_blue_laptop",
		label = "Schematic: Blue Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'blue_laptop',
	},
	{
		name = "schematic_redlaptop",
		label = "Schematic: Red Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'red_laptop',
	},
	{
		name = "schematic_purple_laptop",
		label = "Schematic: Purple Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'purple_laptop',
	},
	{
		name = "schematic_yellow_laptop",
		label = "Schematic: Yellow Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'yellow_laptop',
	},
	{
		name = "schematic_handcuffs",
		label = "Schematic: Handcuffs",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'handcuffs',
	},
	{
		name = "schematic_radio_extendo",
		label = "Schematic: B0085 Radio",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'radio_extendo',
	},
	{
		name = "schematic_38_snubnose",
		label = "Schematic: .38 Snubnose",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'snubnose38',
	},
	{
		name = "schematic_38_custom",
		label = "Schematic: .38 Custom",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'custom38',
	},
	{
		name = "schematic_44_magnum",
		label = "Schematic: .44 Magnum",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'magnum',
	},
	{
		name = "schematic_p226",
		label = "Schematic: P226",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = 'p226',
	},
}