_itemsSource["schematics_weapons"] = {
	{
		name = "schematic_pistol",
		label = "Schematic: Pistol",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'pistol',
	},
	{
		name = "schematic_combat_pistol",
		label = "Schematic: Combat Pistol",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'combatpistol',
	},
	{
		name = "schematic_fnx",
		label = "Schematic: SB 45 Tactical",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'fnx',
	},
	{
		name = "schematic_57",
		label = "Schematic: Six Eight",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'fiveseven',
	},
	{
		name = "schematic_sns",
		label = "Schematic: SNS Pistol",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'sns',
	},
	{
		name = "schematic_snsmk2",
		label = "Schematic: SNS Mk2 Pistol",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'snsmk2',
	},
	{
		name = "schematic_glock",
		label = "Schematic: F19",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'glock',
	},
	{
		name = "schematic_tact2011",
		label = "Schematic: 2011 Tactical",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'tact2011',
	},
	{
		name = "schematic_m9a3",
		label = "Schematic: M9A3",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'm9a3',
	},
	{
		name = "schematic_heavypistol",
		label = "Schematic: Heavy Pistol",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'heavypistol',
	},
	{
		name = "schematic_doubleaction",
		label = "Schematic: Double Action Revolver",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'doubleaction',
	},
	{
		name = "schematic_l5",
		label = "Schematic: Desert Eagle K8",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'l5',
	},
	{
		name = "schematic_deagle",
		label = "Schematic: Desert Eagle",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'deagle',
	},
	{
		name = "schematic_revolver",
		label = "Schematic: Revolver",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'revolver',
	},
	{
		name = "schematic_mp5",
		label = "Schematic: SB54",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mp5',
	},
	{
		name = "schematic_smg",
		label = "Schematic: SMG",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'smg',
	},
	{
		name = "schematic_microsmg",
		label = "Schematic: MAC 10",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'microsmg',
	},
	{
		name = "schematic_tommygun",
		label = "Schematic: Tommy Gun",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'tommygun',
	},
	{
		name = "schematic_smgmk2",
		label = "Schematic: SMG Mk2",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'smgmk2',
	},
	{
		name = "schematic_mpx",
		label = "Schematic: MP 9mm",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mpx',
	},
	{
		name = "schematic_pp19",
		label = "Schematic: PP-19",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'pp19',
	},
	{
		name = "schematic_ump",
		label = "Schematic: .45 SMG",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'ump',
	},
	{
		name = "schematic_p90",
		label = "Schematic: PDW",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'ump',
	},
	{
		name = "schematic_miniuzi",
		label = "Schematic: Mini UZI",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'miniuzi',
	},
	{
		name = "schematic_mp9",
		label = "Schematic: MP9",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mp9',
	},
	{
		name = "schematic_vector",
		label = "Schematic: Vector",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'vector',
	},
	{
		name = "schematic_appistol",
		label = "Schematic: F18 Auto",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'appistol',
	},
	{
		name = "schematic_tec9",
		label = "Schematic: TEC-9",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'tech9',
	},
	{
		name = "schematic_draco",
		label = "Schematic: Draco",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'draco',
	},
	{
		name = "schematic_hk16a",
		label = "Schematic: HK16A",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'hk16a',
	},
	{
		name = "schematic_hk16b",
		label = "Schematic: HK16B",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'hk16b',
	},
	{
		name = "schematic_ar",
		label = "Schematic: AK-47",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'ar',
	},
	{
		name = "schematic_mcxspear",
		label = "Schematic: MCX Spear",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mcxspear',
	},
	{
		name = "schematic_mcxrattler",
		label = "Schematic: MCX Rattler",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mcxrattler',
	},
	{
		name = "schematic_advrifle",
		label = "Schematic: Adv. Rifle",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'advrifle',
	},
	{
		name = "schematic_asval",
		label = "Schematic: AS-VAL",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'asval',
	},
	{
		name = "schematic_nsr9",
		label = "Schematic: NSR9",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'nsr9',
	},
	{
		name = "schematic_g36",
		label = "Schematic: F69",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'g36',
	},
	{
		name = "schematic_ak74",
		label = "Schematic: AK-74",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'ak47',
	},
	{
		name = "schematic_ar15",
		label = "Schematic: AR-15",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'ar15',
	},
	{
		name = "schematic_rpk",
		label = "Schematic: RPK16",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'rpk',
	},
	{
		name = "schematic_honeybadger",
		label = "Schematic: Honey Badger",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'honeybadger',
	},
	{
		name = "schematic_hk417",
		label = "Schematic: HK417",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'hk417',
	},
	{
		name = "schematic_rfb",
		label = "Schematic: RFB",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'rfb',
	},
	{
		name = "schematic_mk47mutant",
		label = "Schematic: MK47 Mutant",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mk47mutant',
	},
	{
		name = "schematic_mk47a",
		label = "Schematic: MK47 A",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mk47a',
	},
	{
		name = "schematic_mk47s",
		label = "Schematic: MK47 S",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = 'mk47s',
	},
}
