local _ran = false

_appData = {
	{
		name = "phone",
		storeLabel = "Phone",
		label = "Phone",
		icon = "phone",
		color = "#21a500",
		params = "",
		internal = {
			{
				app = "call",
				params = ":number?",
			},
			{
				app = "recent",
				params = "",
			},
		},
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "messages",
		storeLabel = "Messages",
		label = "Messages",
		icon = "comment",
		color = "#ff0000",
		params = "",
		internal = {
			{
				app = "new",
			},
			{
				app = "convo",
				params = ":number?",
			},
		},
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "contacts",
		storeLabel = "Contacts",
		label = "Contacts",
		icon = "address-book",
		color = "#ff6a00",
		params = "",
		internal = {
			{
				app = "add",
				params = ":number?",
			},
			{
				app = "view",
				params = ":id",
			},
			{
				app = "caller",
				params = ":id",
			},
		},
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "store",
		storeLabel = "App Store",
		label = "App Store",
		icon = "hippo",
		color = "#ad8d1a",
		params = "",
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "settings",
		storeLabel = "Settings",
		label = "Settings",
		icon = "gear",
		color = "#18191e",
		params = "",
		internal = {
			{
				app = "software",
				params = "",
			},
			{
				app = "profile",
				params = "",
			},
			{
				app = "app_notifs",
				params = "",
			},
			{
				app = "sounds",
				params = "",
			},
			{
				app = "wallpaper",
				params = "",
			},
			{
				app = "colors",
				params = "",
			},
		},
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "email",
		storeLabel = "Email",
		label = "Email",
		icon = "envelope",
		color = "#10909c",
		params = "",
		internal = { {
			app = "view",
			params = ":id?",
		} },
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "bank",
		storeLabel = "Fleeca",
		label = "Fleeca",
		icon = "bank",
		color = "#268f3a",
		params = "",
		canUninstall = true,
		store = true,
		unread = 0,
		requirements = {},
		internal = {
			{
				app = "view",
				params = ":account",
			},
			{
				app = "bill",
				params = "",
			},
		},
	},
	{
		name = "loans",
		storeLabel = "Loans",
		label = "Loans",
		icon = { "far", "money-check-dollar" },
		color = "#30a60f",
		params = "",
		canUninstall = true,
		store = true,
		unread = 0,
		requirements = {},
		internal = {
			{
				app = "view",
				params = ":loan",
			},
		},
	},
	{
		name = "twitter",
		storeLabel = "Spammer",
		label = "Spammer",
		icon = { "far", "face-awesome" },
		color = "#c4b404",
		params = "",
		canUninstall = true,
		store = true,
		unread = 0,
		requirements = {},
		internal = {
			{
				app = "profile",
				params = "",
			},
		},
	},
	{
		name = "chatter",
		storeLabel = "Chatter",
		label = "Chatter",
		icon = { "fab", "rocketchat" },
		color = "#2d2835",
		params = "",
		canUninstall = true,
		store = true,
		unread = 0,
		internal = {
			{
				app = "channel",
				params = ":channel",
			},
			{
				app = "join",
				params = ":channel",
			},
			{
				app = "config",
				params = ":channel",
			},
			{
				app = "invites",
				params = "",
			},
		},
		requirements = {},
	},
	{
		name = "adverts",
		storeLabel = "Ads",
		label = "Ads",
		icon = { "fab", "adversal" },
		color = "#870b30",
		params = "",
		unread = 0,
		internal = {
			{
				app = "view",
				params = ":id",
			},
			{
				app = "category-view",
				params = ":category",
			},
			{
				app = "add",
				params = "",
			},
			{
				app = "edit",
				params = "",
			},
		},
		canUninstall = true,
		store = true,
		requirements = {},
	},
	{
		name = "redline",
		storeLabel = "Redline",
		label = "Redline",
		icon = { "far", "gauge-simple-high" },
		color = "#9d1614",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
		restricted = {
			state = "RACE_DONGLE",
		},
		internal = {
			{
				app = "completed",
				params = "",
			},
			{
				app = "new",
				params = "",
			},
			{
				app = "admin",
				params = "",
			},
			{
				app = "view",
				params = ":race",
			},
			{
				app = "profile",
				params = ":racer",
			},
			{
				app = "tracks",
				params = ":track?",
			},
			{
				app = "invites",
				params = "",
			},
		},
	},
	{
		name = "blueline",
		storeLabel = "Trials",
		label = "Trials",
		icon = { "far", "stopwatch-20" },
		color = "#1258a3",
		params = ":tab?",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
		restricted = {
			job = {
				police = 1,
			},
		},
		internal = {
			{
				app = "completed",
				params = "",
			},
			{
				app = "new",
				params = "",
			},
			{
				app = "admin",
				params = "",
			},
			{
				app = "view",
				params = ":race",
			},
		},
	},
	{
		name = "comanager",
		storeLabel = "BizWiz",
		label = "BizWiz",
		icon = "briefcase",
		color = "#db5004",
		params = "",
		hidden = false,
		canUninstall = false,
		store = false,
		unread = 0,
		internal = {
			{
				app = "view",
				params = ":jobId",
			},
		},
	},
	{
		name = "labor",
		storeLabel = "Jobs",
		label = "Jobs",
		icon = { "fad", "pickaxe" },
		color = "#05737d",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "crypto",
		storeLabel = "DigiDollar",
		label = "DigiDollar",
		icon = { "far", "circle-dollar" },
		color = "#354f34",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "dyn8",
		storeLabel = "Dynasty 8",
		label = "Dynasty 8",
		icon = { "fad", "sign-hanging" },
		color = "#136231",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
		restricted = {
			job = {
				--realestate = 1,
				penis = 1,
			},
		},
	},
	{
		name = "homemanage",
		storeLabel = "Properties",
		label = "Properties",
		icon = "house-signal",
		color = "#362a4f",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "garage",
		storeLabel = "Garage",
		label = "Garage",
		icon = "car-garage",
		color = "#50ba13",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
		internal = {
			{
				app = "view",
				params = ":vin",
			},
		},
	},
	{
		name = "pingem",
		storeLabel = "FINDR",
		label = "FINDR",
		icon = "map-pin",
		color = "#e3db02",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "calculator",
		storeLabel = "Calculator",
		label = "Calculator",
		icon = "calculator-simple",
		color = "#E95200",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		storeLabel = "Documents",
		label = "Documents",
		icon = "file-lines",
		name = "documents",
		color = "#820366",
		canUninstall = true,
		unread = 0,
		params = "",
		internal = {
			{
				app = "view",
				params = ":id",
			},
			{
				app = "new",
				params = "",
			},
			{
				app = "edit",
				params = ":id",
			},
		},
	},
	{
		name = "services",
		storeLabel = "Services",
		label = "Services",
		icon = "clipboard-list",
		color = "#E95200",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "chopper",
		storeLabel = "Chopper",
		label = "Chopper",
		icon = "axe",
		color = "#8800c7",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
		restricted = {
			state = "ACCESS_CHOPPER",
		},
	},
	{
		name = "media",
		storeLabel = "Media",
		label = "Media",
		icon = "photo-film",
		color = "#59E5F7",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "music",
		storeLabel = "Music",
		label = "Music",
		icon = "cloud-music",
		color = "#63e6be",
		params = "",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
}
