table.insert(Config.Businesses, {
	Job = "jewel",
	Name = "The Jeweled Dragon",
	Benches = {
		jewelry = {
			label = "",
			targeting = {
				actionString = "Making",
				manual = true,
			},
			recipes = {
				{
					result = { name = "mint_mate_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "mint_mate_chain_2", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "ssb_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 2 },
						{ name = "diamond", count = 1 }, -- add diamond since amethysts are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "gotti_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 2 },
						{ name = "diamond", count = 1 }, -- add diamond since sapphires are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "uwu_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 1 },
						{ name = "opal", count = 2 },
						{ name = "diamond", count = 1 }, -- add diamond since amethysts are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "pixels_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "megaphone", count = 1 },
						{ name = "diamond", count = 1 }, -- add diamond since amethysts are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "frosty_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "milk_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "saint_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "bobs_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "lala_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "emerald", count = 1 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "rooks_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "deathrow_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 15 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "ferrari_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 15 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "dynasty_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "oni_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 15 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "snowboiz_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "mint_mate_chain_3", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "boo_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "krazed_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "snow_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "rush_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "meg_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "olivia_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "diamond_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "britton_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 30 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "ssf_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "bigpoppa_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "skull_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "pimpdaddy_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "richardson_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "king_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "unicorn_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "unity_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "pizzathis_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
						{ name = "opal", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "ottos_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "duck_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 2 },
						{ name = "citrine", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "dani_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "armytags_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "sapphire", count = 1 },
						{ name = "citrine", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "donut_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "mustard_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 5 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "pandanoodle_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 4 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "famli_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "pgs_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "bdragon_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "doublecup_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "axel_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "sage_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 4 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "fredo_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "hajaar_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 5 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "diablos_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "ninezero_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 5 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "otf_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 5 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "nolan_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "olivia2_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "him_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "nos_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "eb13_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 5 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "tracy_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "oggramps_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "cloud9_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "dex_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "queen_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 3 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "takia_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 3 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "nines_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "vell_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "jrawefg_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "bco_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "paletotuner_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "illuminati_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "produce_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
						{ name = "amethyst", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "bandits_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "amethyst", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "mafia_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "one41_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				-- {
				-- 	result = { name = "streetlegends_chain", count = 1 },
				-- 	items = {
				-- 		{ name = "goldbar", count = 10 },
				-- 		{ name = "silverbar", count = 20 },
				-- 		{ name = "diamond", count = 1 },
				-- 		{ name = "ruby", count = 1 },
				-- 		{ name = "opal", count = 5 },
				-- 	},
				-- 	time = 6500,
				-- },
				{
					result = { name = "summer_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "esb_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "shlevin_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "moneybag_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "bluediamond_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "wolfring_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "smiley_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "him2_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "sbc_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "fafo_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "weed_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "queenies_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "hbdatsme_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "dagoat_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "billyhale_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "ten13_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "deathrow2_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "turtles_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "mostwanted_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "spencer_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "santamuerte_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 1 },
						{ name = "amethyst", count = 4 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "egan_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "moneymind_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
			},
		},
	},
	Storage = {
		{
			id = "jewel-gem-storage-1",
			type = "box",
			coords = vector3(-698.615, -902.925, 19.525),
			length = 1.0,
			width = 1.0,
			options = {
				heading = 270.623,
				--debugPoly=true,
				minZ = 18.525,
				maxZ = 20.525,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 151,
					owner = "jewel-office-storage-1",
				},
			},
		},
		{
			id = "jewel-gem-storage-2",
			type = "box",
			coords = vector3(-707.823, -892.020, 19.525),
			length = 0.5,
			width = 3.0,
			options = {
				heading = 0.0,
				--debugPoly=true,
				minZ = 18.525,
				maxZ = 20.525,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 152,
					owner = "jewel-office-storage-2",
				},
			},
		},
		{
			id = "jewel-safe-1",
			type = "box",
			coords = vector3(-710.585, -898.925, 19.525),
			length = 4.0,
			width = 3.4,
			options = {
				heading = 180.876,
				--debugPoly=true,
				minZ = 18.525,
				maxZ = 20.525,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 150,
					owner = "jewel-safe-1",
				},
			},
		},
		{
			id = "jewel-storage-1",
			type = "box",
			coords = vector3(-698.491, -899.153, 23.806),
			length = 1.0,
			width = 1.0,
			options = {
				heading = 275.623,
				--debugPoly=true,
				minZ = 22.806,
				maxZ = 24.806,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 154,
					owner = "jewel-storage-1",
				},
			},
		},
		{
			id = "jewel-storage-2",
			type = "box",
			coords = vector3(-703.913, -893.902, 19.525),
			length = 5.0,
			width = 4.0,
			options = {
				heading = 0.0,
				--debugPoly=true,
				minZ = 18.525,
				maxZ = 20.525,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 153,
					owner = "jewel-storage-1",
				},
			},
		},
	},
	Pickups = {
		{
			id = "jewel-pickup-1",
			coords = vector3(-712.705, -895.634, 23.795),
			width = 1.0,
			length = 2.0,
			options = {
				heading = 90,
				--debugPoly=true,
				minZ = 22.795,
				maxZ = 24.795,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 25,
					owner = "jewel-pickup-1",
				},
			},
		},
		{
			id = "jewel-pickup-2",
			coords = vector3(-705.103, -895.943, 23.795),
			width = 1.0,
			length = 2.0,
			options = {
				heading = 270.0,
				--debugPoly=true,
				minZ = 22.795,
				maxZ = 24.795,
			},
			data = {
				business = "jewel",
				inventory = {
					invType = 155,
					owner = "jewel-pickup-2",
				},
			},
		},
	},
})
