table.insert(Config.Businesses, {
	Job = "vangelico",
	Name = "Vangelico Jewelry",
	Benches = {
		jewelry = {
			label = "",
			targeting = {
				actionString = "Making",
				manual = true,
			},
			recipes = {
				{
					result = { name = "mint_mate_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "mint_mate_chain_2", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "ssb_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 2 },
						{ name = "diamond", count = 1 }, -- add diamond since amethysts are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "gotti_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 2 },
						{ name = "diamond", count = 1 }, -- add diamond since sapphires are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "uwu_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 1 },
						{ name = "opal", count = 2 },
						{ name = "diamond", count = 1 }, -- add diamond since amethysts are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "pixels_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "megaphone", count = 1 },
						{ name = "diamond", count = 1 }, -- add diamond since amethysts are so much more common than emeralds
					},
					time = 6500,
				},
				{
					result = { name = "frosty_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "milk_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "saint_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "bobs_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "lala_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "emerald", count = 1 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "rooks_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "deathrow_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 15 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "ferrari_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 15 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "dynasty_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "oni_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 15 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "snowboiz_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "mint_mate_chain_3", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "boo_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "krazed_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "snow_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "rush_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "meg_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "olivia_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "diamond_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "britton_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 30 },
						{ name = "diamond", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "ssf_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "bigpoppa_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 2 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "skull_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "pimpdaddy_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "richardson_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "king_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "unicorn_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "unity_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "pizzathis_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
						{ name = "opal", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "ottos_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "duck_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 2 },
						{ name = "citrine", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "dani_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "armytags_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "sapphire", count = 1 },
						{ name = "citrine", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "donut_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "ruby", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "mustard_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 5 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "pandanoodle_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 4 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "famli_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "pgs_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "bdragon_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "doublecup_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 4 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "axel_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "sage_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 4 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "fredo_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "citrine", count = 4 },
					},
					time = 6500,
				},
				{
					result = { name = "hajaar_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 5 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "diablos_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "ninezero_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 5 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "otf_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 5 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "nolan_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "olivia2_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "him_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "nos_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "eb13_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "citrine", count = 5 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "tracy_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "amethyst", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "oggramps_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "cloud9_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "dex_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "queen_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 3 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "takia_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "amethyst", count = 3 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "nines_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "vell_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "jrawefg_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "bco_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "paletotuner_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "illuminati_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "produce_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
						{ name = "amethyst", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "bandits_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "amethyst", count = 3 },
					},
					time = 6500,
				},
				{
					result = { name = "mafia_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "one41_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				-- {
				-- 	result = { name = "streetlegends_chain", count = 1 },
				-- 	items = {
				-- 		{ name = "goldbar", count = 10 },
				-- 		{ name = "silverbar", count = 20 },
				-- 		{ name = "diamond", count = 1 },
				-- 		{ name = "ruby", count = 1 },
				-- 		{ name = "opal", count = 5 },
				-- 	},
				-- 	time = 6500,
				-- },
				{
					result = { name = "summer_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "ruby", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "esb_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "shlevin_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "moneybag_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "bluediamond_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "wolfring_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "smiley_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "him2_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "sbc_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "amethyst", count = 3 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "fafo_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "weed_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "emerald", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "queenies_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "hbdatsme_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "ruby", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "dagoat_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "billyhale_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "ten13_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "deathrow2_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "turtles_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "sapphire", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "mostwanted_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "spencer_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "sapphire", count = 1 },
						{ name = "diamond", count = 1 },
						{ name = "opal", count = 5 },
					},
					time = 6500,
				},
				{
					result = { name = "santamuerte_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 1 },
						{ name = "amethyst", count = 4 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
				{
					result = { name = "egan_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "opal", count = 5 },
						{ name = "diamond", count = 2 },
					},
					time = 6500,
				},
				{
					result = { name = "moneymind_chain", count = 1 },
					items = {
						{ name = "goldbar", count = 10 },
						{ name = "silverbar", count = 20 },
						{ name = "emerald", count = 1 },
						{ name = "ruby", count = 1 },
						{ name = "diamond", count = 1 },
					},
					time = 6500,
				},
			},
		},
	},
	Storage = {
		{
			id = "vangelico-safe-1",
			type = "box",
			coords = vector3(-383.68, 6052.27, 31.51),
			length = 1,
			width = 1.4,
			options = {
				heading = 315.0,
				--debugPoly=true,
				minZ = 30.11,
				maxZ = 32.71,
			},
			data = {
				business = "vangelico",
				inventory = {
					invType = 193,
					owner = "vangelico-safe-1",
				},
			},
		},
		{
			id = "vangelico-storage-1",
			type = "box",
			coords = vector3(-384.58, 6050.94, 31.51),
			length = 2.2,
			width = 2.0,
			options = {
				heading = 315.0,
				--debugPoly=true,
				minZ = 29.11,
				maxZ = 33.11,
			},
			data = {
				business = "vangelico",
				inventory = {
					invType = 194,
					owner = "vangelico-storage-1",
				},
			},
		},
		{
			id = "vangelico-storage-2",
			type = "box",
			coords = vector3(-379.68, 6049.42, 31.51),
			length = 1.4,
			width = 1.0,
			options = {
				heading = 45.0,
				--debugPoly=true,
				minZ = 28.71,
				maxZ = 32.71,
			},
			data = {
				business = "vangelico",
				inventory = {
					invType = 210,
					owner = "vangelico-storage-2",
				},
			},
		},
	},
	Pickups = {
		{
			id = "vangelico-pickup-1",
			coords = vector3(-383.27, 6045.62, 31.51),
			width = 1.2,
			length = 0.65,
			options = {
				heading = 315,
				--debugPoly=true,
				minZ = 30.31,
				maxZ = 32.11,
			},
			data = {
				business = "vangelico",
				inventory = {
					invType = 195,
					owner = "vangelico-pickup-1",
				},
			},
		},
	},
})
