_itemsSource["erp"] = {
	{
		name = "buttplug_black",
		label = "Butt Plug",
		description = "Part of the Uranus Butt Plug Corporation.",
		price = 200,
		isUsable = true,
		isStackable = false,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = "buttplug_pink",
		label = "Butt Plug",
		description = "Part of the Uranus Butt Plug Corporation.",
		price = 200,
		isUsable = true,
		isStackable = false,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = "vibrator_pink",
		label = "Vibrator",
		description = "If you vibe it, they will cum.",
		price = 400,
		isUsable = true,
		isStackable = false,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
}
