_itemsSource["signs"] = {
	{
		name = "sign_dontblock",
		label = "Do Not Block Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = "sign_leftturn",
		label = "Left Turn Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = "sign_nopark",
		label = "No Parking Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "sign_notresspass",
		label = "No Tresspassing Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "sign_rightturn",
		label = "Right Turn Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "sign_stop",
		label = "Stop Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "sign_uturn",
		label = "U-Turn Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "sign_walkingman",
		label = "Walking Man Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "sign_yield",
		label = "Yield Sign",
		description = "Where did this come from?",
		price = 200,
		isUsable = true,
		isStackable = 25,
		isDestroyed = false,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
}
