_itemsSource["unique"] = {
	{
		name = "mint_mate_chain",
		label = "Mint Mate Chain",
		description = "It's Mint Mate",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate",
		iconOverride = "rlg_chain",
	},
	{
		name = "mint_mate_chain_2",
		label = "Mint Mate Chain (Large)",
		description = "It's Mint Mate ... but large",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate2",
		iconOverride = "rlg_chain",
	},
	{
		name = "ssb_chain",
		label = "SSB Chain",
		description = "SSB Gang Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssb",
		iconOverride = "rlg_chain",
	},
	{
		name = "gotti_chain",
		label = "Gotti Family Chain",
		description = "Gotti Family Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "gotti",
		iconOverride = "rlg_chain",
	},
	{
		name = "uwu_chain",
		label = "UwU Chain",
		description = "UwU Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "uwu",
		iconOverride = "rlg_chain",
	},
	{
		name = "pixels_chain",
		label = "Business Bureau Chain",
		description = "Business Bureau Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "lua",
		iconOverride = "rlg_chain",
	},
	{
		name = "frosty_chain",
		label = "Frosty Chain",
		description = "Frosty Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "frosty",
		iconOverride = "rlg_chain",
	},
	{
		name = "milk_chain",
		label = "Milk Chain",
		description = "Milk Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "milk",
		iconOverride = "rlg_chain",
	},
	{
		name = "saint_chain",
		label = "Saint Chain",
		description = "Saint Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "saint",
		iconOverride = "rlg_chain",
	},
	{
		name = "bobs_chain",
		label = "Bob's Balls Chain",
		description = "Bob's Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bobs",
		iconOverride = "rlg_chain",
	},
	{
		name = "lala_chain",
		label = "Tequi-La-La Chain",
		description = "Tequi-La-La Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "lala",
		iconOverride = "rlg_chain",
	},
	{
		name = "rooks_chain",
		label = "Rooks Chain",
		description = "Rooks Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "rooks",
		iconOverride = "rlg_chain",
	},
	{
		name = "deathrow_chain",
		label = "Death Row Chain",
		description = "Death Row Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "deathrow",
		iconOverride = "rlg_chain",
	},
	{
		name = "ferrari_chain",
		label = "Ferrari Family Chain",
		description = "Ferrari Family Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ferrari",
		iconOverride = "rlg_chain",
	},
	{
		name = "dynasty_chain",
		label = "Dynasty Chain",
		description = "Dynasty Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "dynasty",
		iconOverride = "rlg_chain",
	},
	{
		name = "oni_chain",
		label = "Oni Chain",
		description = "Oni Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "oni",
		iconOverride = "rlg_chain",
	},
	{
		name = "snowboiz_chain",
		label = "Snow Boiz Chain",
		description = "Snow Boiz Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "snowboiz",
		iconOverride = "rlg_chain",
	},
	{
		name = "mint_mate_chain_3",
		label = "Mint Mate Chain (Alternate)",
		description = "It's Mint Mate",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate3",
		iconOverride = "rlg_chain",
	},
	{
		name = "boo_chain",
		label = "BOO Chain",
		description = "BOO!",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "boo",
		iconOverride = "rlg_chain",
	},
	{
		name = "krazed_chain",
		label = "Krazed Ridez Chain",
		description = "Krazed Ridez Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "krazed",
		iconOverride = "rlg_chain",
	},
	{
		name = "snow_chain",
		label = "Snow Chain",
		description = "Snow Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "snow",
		iconOverride = "rlg_chain",
	},
	{
		name = "rush_chain",
		label = "Rush Chain",
		description = "Rush Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "rush",
		iconOverride = "rlg_chain",
	},
	{
		name = "meg_chain",
		label = "Meg Chain",
		description = "Meg Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "meg",
		iconOverride = "rlg_chain",
	},
	{
		name = "olivia_chain",
		label = "Vangelico Chain",
		description = "Vangelico Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "olivia",
		iconOverride = "rlg_chain",
	},
	{
		name = "diamond_chain",
		label = "Olivia Chain",
		description = "Olivia Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "diamond",
		iconOverride = "rlg_chain",
	},
	{
		name = "britton_chain",
		label = "Britton Chain",
		description = "Britton Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "britton",
		iconOverride = "rlg_chain",
	},
	{
		name = "ssf_chain",
		label = "SSF Chain",
		description = "SSF Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssf",
		iconOverride = "rlg_chain",
	},
	{
		name = "bigpoppa_chain",
		label = "Big Poppa Chain",
		description = "Big Poppa Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bigpoppa",
		iconOverride = "rlg_chain",
	},
	{
		name = "skull_chain",
		label = "Thick Skull Chain",
		description = "Thick Skull Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "skull",
		iconOverride = "rlg_chain",
	},
	{
		name = "pimpdaddy_chain",
		label = "Pimp Daddy Chain",
		description = "Pimp Daddy Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "pimpdaddy",
		iconOverride = "rlg_chain",
	},
	{
		name = "richardson_chain",
		label = "Richardson Chain",
		description = "Richardson Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "richardson",
		iconOverride = "rlg_chain",
	},
	{
		name = "king_chain",
		label = "King Crown Chain",
		description = "King Crown Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "king",
		iconOverride = "rlg_chain",
	},
	{
		name = "unicorn_chain",
		label = "Unicorn Chain",
		description = "Unicorn Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "unicorn",
		iconOverride = "rlg_chain",
	},
	{
		name = "unity_chain",
		label = "The Unity Chain",
		description = "The Unity Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "unity",
		iconOverride = "rlg_chain",
	},
	{
		name = "pizzathis_chain",
		label = "Pizza This Chain",
		description = "Pizza This Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "pizzathis",
		iconOverride = "rlg_chain",
	},
	{
		name = "ottos_chain",
		label = "Otto's Chain",
		description = "Otto's Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ottos",
		iconOverride = "rlg_chain",
	},
	{
		name = "duck_chain",
		label = "Duck Chain",
		description = "Duck Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "duck",
		iconOverride = "rlg_chain",
	},
	{
		name = "dani_chain",
		label = "Dani Chain",
		description = "Dani Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "dani",
		iconOverride = "rlg_chain",
	},
	{
		name = "armytags_chain",
		label = "Army Dog Tag Chain",
		description = "Army Dog Tag Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "armytags",
		iconOverride = "rlg_chain",
	},
	{
		name = "donut_chain",
		label = "Donut Chain",
		description = "Donut Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "donut",
		iconOverride = "rlg_chain",
	},
	{
		name = "mustard_chain",
		label = "Mustard Chain",
		description = "Mustard Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mustard",
		iconOverride = "rlg_chain",
	},
	{
		name = "pandanoodle_chain",
		label = "Panda Noodle Chain",
		description = "Panda Noodle Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "pandanoodle",
		iconOverride = "rlg_chain",
	},
	{
		name = "famli_chain",
		label = "Teal’s Chain",
		description = "Teal’s Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "famli",
		iconOverride = "rlg_chain",
	},
	{
		name = "pgs_chain",
		label = "PGS Chain",
		description = "PGS Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "pgs",
		iconOverride = "rlg_chain",
	},
	{
		name = "bdragon_chain",
		label = "BlackDragon Chain",
		description = "BlackDragon Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bdragon",
		iconOverride = "rlg_chain",
	},
	{
		name = "doublecup_chain",
		label = "Double Cup Chain",
		description = "2 is a party!",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "doublecup",
		iconOverride = "rlg_chain",
	},
	{
		name = "axel_chain",
		label = "Axel Chain",
		description = "Axel Chain and jewelry",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "axel",
		iconOverride = "rlg_chain",
	},
	{
		name = "sage_chain",
		label = "Bear Chain",
		description = "Bear Chain - Female",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "sage",
		iconOverride = "rlg_chain",
	},
	{
		name = "fredo_chain",
		label = "Fredo Chain",
		description = "Fredo Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "fredo",
		iconOverride = "rlg_chain",
	},
	{
		name = "hajaar_chain",
		label = "Hajaar Chain",
		description = "Hajaar Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "hajaar",
		iconOverride = "rlg_chain",
	},
	{
		name = "diablos_chain",
		label = "Diablos Chain",
		description = "Diablos Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "diablos",
		iconOverride = "rlg_chain",
	},
	{
		name = "ninezero_chain",
		label = "9Zero Chain",
		description = "9Zero Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ninezero",
		iconOverride = "rlg_chain",
	},
	{
		name = "otf_chain",
		label = "OTF Chain",
		description = "OTF Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "otf",
		iconOverride = "rlg_chain",
	},
	{
		name = "nolan_chain",
		label = "Nolan Chain",
		description = "Nolan Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "nolan",
		iconOverride = "rlg_chain",
	},
	{
		name = "olivia2_chain",
		label = "Olivia Chain",
		description = "Olivia Chain - female",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "olivia2",
		iconOverride = "rlg_chain",
	},
	{
		name = "him_chain",
		label = "I'm Him Chain",
		description = "I'm HIM Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "him",
		iconOverride = "rlg_chain",
	},
	{
		name = "nos_chain",
		label = "NOS Chain",
		description = "LIGHTNING FAST",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "nos",
		iconOverride = "rlg_chain",
	},
	{
		name = "eb13_chain",
		label = "EB13 Chain",
		description = "EB13 Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "eb13",
		iconOverride = "rlg_chain",
	},
	{
		name = "tracy_chain",
		label = "Tracy Chain",
		description = "WOOP WOOP Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "tracy",
		iconOverride = "rlg_chain",
	},
	{
		name = "oggramps_chain",
		label = "OG Gramps Chain",
		description = "OG Gramps' Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "oggramps",
		iconOverride = "rlg_chain",
	},
	{
		name = "cloud9_chain",
		label = "Cloud9 Chain",
		description = "Cloud9 Drifting Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "cloud9",
		iconOverride = "rlg_chain",
	},
	{
		name = "dex_chain",
		label = "Dex Chain",
		description = "Dex Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "dex",
		iconOverride = "rlg_chain",
	},
	{
		name = "takia_chain",
		label = "Takia Chain",
		description = "Takia Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "takia",
		iconOverride = "rlg_chain",
	},
	{
		name = "queen_chain",
		label = "Queen Chain",
		description = "Queen Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "queen",
		iconOverride = "rlg_chain",
	},
	{
		name = "nines_chain",
		label = "The 9's Chain",
		description = "9's Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "nines",
		iconOverride = "rlg_chain",
	},
	{
		name = "vell_chain",
		label = "Vell's Chain",
		description = "Vell's Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "vell",
		iconOverride = "rlg_chain",
	},
	{
		name = "jrawefg_chain",
		label = "FG Chain",
		description = "FG Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "jrawefg",
		iconOverride = "rlg_chain",
	},
	{
		name = "bco_chain",
		label = "Broward Boy Chain",
		description = "Broward Boy Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bco",
		iconOverride = "rlg_chain",
	},
	{
		name = "paletotuner_chain",
		label = "Paleto Tuner Chain",
		description = "Paleto Tuner Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "paletotuner",
		iconOverride = "rlg_chain",
	},
	{
		name = "illuminati_chain",
		label = "Illuminati Chain",
		description = "Illuminati Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "illuminati",
		iconOverride = "rlg_chain",
	},
	{
		name = "produce_chain",
		label = "Produce Crew Chain",
		description = "Produce Crew Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "produce",
		iconOverride = "rlg_chain",
	},
	{
		name = "bandits_chain",
		label = "Bandits Chain",
		description = "Bandits Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bandits",
		iconOverride = "rlg_chain",
	},
	{
		name = "mafia_chain",
		label = "Escobar Mafia Chain",
		description = "Escobar Mafia Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mafia",
		iconOverride = "rlg_chain",
	},
	{
		name = "one41_chain",
		label = "141 Chain",
		description = "141 Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "one41",
		iconOverride = "rlg_chain",
	},
	{
		name = "streetlegends_chain",
		label = "Street Legends Chain",
		description = "Street Legends Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "streetlegends",
		iconOverride = "rlg_chain",
	},
	{
		name = "summer_chain",
		label = "Summer Chain",
		description = "Summer Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "summer",
		iconOverride = "rlg_chain",
	},
	{
		name = "esb_chain",
		label = "ESB Chain",
		description = "ESB Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "esb",
		iconOverride = "rlg_chain",
	},
	{
		name = "shlevin_chain",
		label = "Shlevin Chain",
		description = "Shlevin Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "shlevin",
		iconOverride = "rlg_chain",
	},
	{
		name = "moneybag_chain",
		label = "Money Bag Chain",
		description = "Money Bag Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "moneybag",
		iconOverride = "rlg_chain",
	},
	{
		name = "bluediamond_chain",
		label = "Blue Diamond Chain",
		description = "Blue Diamond Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bluediamond",
		iconOverride = "rlg_chain",
	},
	{
		name = "wolfring_chain",
		label = "G.S. Wolf Ring",
		description = "Wolf Ring",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "wolfring",
		iconOverride = "ring",
	},
	{
		name = "smiley_chain",
		label = "Smiley Chain",
		description = "Why so serious?",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "smiley",
		iconOverride = "rlg_chain",
	},
	{
		name = "him2_chain",
		label = "I'm Him Chain 2",
		description = "I'm Him Chain 2",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "him2",
		iconOverride = "rlg_chain",
	},
	{
		name = "sbc_chain",
		label = "SBC Chain",
		description = "SBC Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "sbc",
		iconOverride = "rlg_chain",
	},
	{
		name = "fafo_chain",
		label = "FAFO Chain",
		description = "FAFO Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "fafo",
		iconOverride = "rlg_chain",
	},
	{
		name = "weed_chain",
		label = "Weed Chain",
		description = "Weed Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "weed",
		iconOverride = "rlg_chain",
	},
	{
		name = "queenies_chain",
		label = "Queenies Chain",
		description = "Queenies Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "queenies",
		iconOverride = "rlg_chain",
	},
	{
		name = "hbdatsme_chain",
		label = "HB Chain",
		description = "HBDATSME yo",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "hbdatsme",
		iconOverride = "rlg_chain",
	},
	{
		name = "dagoat_chain",
		label = "DaGOAT Chain",
		description = "DaGOAT Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "dagoat",
		iconOverride = "rlg_chain",
	},
	{
		name = "billyhale_chain",
		label = "Calilly Chain",
		description = "Calilly Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "billyhale",
		iconOverride = "rlg_chain",
	},
	{
		name = "ten13_chain",
		label = "1013 Chain",
		description = "1013 Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ten13",
		iconOverride = "rlg_chain",
	},
	{
		name = "deathrow2_chain",
		label = "Death Row Chain 2",
		description = "Death Row Chain 2",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "deathrow2",
		iconOverride = "rlg_chain",
	},
	{
		name = "turtles_chain",
		label = "Ice Ice Turtle Chain",
		description = "I like turtles",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "turtles",
		iconOverride = "rlg_chain",
	},
	{
		name = "mostwanted_chain",
		label = "Most Wanted Chain",
		description = "Most Wanted Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mostwanted",
		iconOverride = "rlg_chain",
	},
	{
		name = "spencer_chain",
		label = "41 Spencer Chain",
		description = "41 Spencer Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "spencer",
		iconOverride = "rlg_chain",
	},
	{
		name = "santamuerte_chain",
		label = "Santa Muerte Chain",
		description = "Santa Muerte Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "santamuerte",
		iconOverride = "rlg_chain",
	},
	{
		name = "egan_chain",
		label = "Egan Chain",
		description = "Egan Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "egan",
		iconOverride = "rlg_chain",
	},
	{
		name = "moneymind_chain",
		label = "Money on the Mind Chain",
		description = "Money on the Mind Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "moneymind",
		iconOverride = "rlg_chain",
	},
}
