_itemsSource["weapons_bobcat"] = {
	{
		name = "BOBCAT_57",
		label = "Six Eight",
		weapon = "WEAPON_FIVESEVEN",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_FIVESEVEN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_M9A3",
		label = "M9A3",
		weapon = "WEAPON_FM1_M9A3",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_FM1_M9A3",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_2011",
		label = "2011 Tactical",
		weapon = "WEAPON_2011",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_2011",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_FNX",
		label = "SB 45 Tactical",
		weapon = "WEAPON_FNX",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_FNX",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_GLOCK19_CIV",
		label = "F19",
		iconOverride = "WEAPON_GLOCK19",
		weapon = "WEAPON_GLOCK19_CIV",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_SNSPISTOL",
		label = "SNS Pistol",
		weapon = "WEAPON_SNSPISTOL",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_SNSPISTOL",
		requiresLicense = true,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = "BOBCAT_COMBATPISTOL",
		label = "Combat Pistol",
		weapon = "WEAPON_COMBATPISTOL",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_COMBATPISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_DOUBLEACTION",
		label = "Double Action Revolver",
		weapon = "WEAPON_DOUBLEACTION",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_DOUBLEACTION",
		requiresLicense = true,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_PISTOL50",
		label = "Desert Eagle",
		weapon = "WEAPON_PISTOL50",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_PISTOL50",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_L5",
		label = "Desert Eagle K8",
		weapon = "WEAPON_L5",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_L5",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_REVOLVER",
		label = "Revolver",
		weapon = "WEAPON_REVOLVER",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_REVOLVER",
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_SMG_MK2",
		label = "SIG MPX",
		weapon = "WEAPON_SMG_MK2",
		ammoType = "AMMO_SMG",
		iconOverride = "WEAPON_SMG_MK2",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_SAWNOFFSHOTGUN",
		label = "Sawnoff Shotgun",
		weapon = "WEAPON_SAWNOFFSHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		iconOverride = "WEAPON_SAWNOFFSHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_PUMPSHOTGUN",
		label = "Pump Shotgun",
		weapon = "WEAPON_PUMPSHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		iconOverride = "WEAPON_PUMPSHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "BOBCAT_DBSHOTGUN",
		label = "Double Barrel Shotgun",
		weapon = "WEAPON_DBSHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		iconOverride = "WEAPON_DBSHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_PP19",
		label = "PP-19",
		weapon = "WEAPON_PP19",
		ammoType = "AMMO_SMG",
		iconOverride = "WEAPON_PP19",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_MPX",
		label = "MP 9mm",
		weapon = "WEAPON_MPX",
		ammoType = "AMMO_SMG",
		iconOverride = "WEAPON_MPX",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_MP9A",
		label = "MP9",
		weapon = "WEAPON_MP9A",
		ammoType = "AMMO_SMG",
		iconOverride = "WEAPON_MP9A",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_MINIUZI",
		label = "Mini UZI",
		weapon = "WEAPON_MINIUZI",
		ammoType = "AMMO_SMG",
		iconOverride = "WEAPON_MINIUZI",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_MCXSPEAR",
		label = "SBX Spear",
		weapon = "WEAPON_MCXSPEAR",
		ammoType = "AMMO_RIFLE",
		iconOverride = "WEAPON_MCXSPEAR",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_COMPACTRIFLE",
		label = "Draco",
		weapon = "WEAPON_COMPACTRIFLE",
		ammoType = "AMMO_RIFLE",
		iconOverride = "WEAPON_COMPACTRIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_38SNUBNOSE2",
		label = ".38 Snubnose",
		weapon = "WEAPON_38SNUBNOSE2",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_38SNUBNOSE2",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_38SNUBNOSE3",
		label = ".38 Snubnose",
		weapon = "WEAPON_38SNUBNOSE3",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_38SNUBNOSE3",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_38CUSTOM",
		label = ".38 Custom",
		weapon = "WEAPON_38SPECIAL",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_38SPECIAL",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_44MAGNUM",
		label = ".44 Magnum",
		weapon = "WEAPON_44MAGNUM",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_44MAGNUM",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "BOBCAT_P226",
		label = "P226",
		weapon = "WEAPON_FM1_P226",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_FM1_P226",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
}
