Config = Config or {}

Config.Weapons = {
	[`WEAPON_FALLING`] = { minor = true },
	[`WEAPON_UNARMED`] = { minor = true },
	[`WEAPON_ANIMAL`] = { minor = true },
	[`WEAPON_COUGAR`] = { minor = false },
	[`WEAPON_KNIFE`] = { minor = false, violent = true },
	[`WEAPON_SWITCHBLADE`] = { minor = false, violent = true },
	[`WEAPON_SHIV`] = { minor = false, violent = true },
	[`WEAPON_KATANA`] = { minor = false, violent = true },
	[`WEAPON_NIGHTSTICK`] = { minor = true, violent = true },
	[`WEAPON_HAMMER`] = { minor = true, violent = true },
	[`WEAPON_BAT`] = { minor = true },
	[`WEAPON_GOLFCLUB`] = { minor = true, violent = true },
	[`WEAPON_CROWBAR`] = { minor = true, violent = true },
	[`WEAPON_SLEDGEHAMMER`] = { minor = true },
	[`WEAPON_PONY`] = { minor = true },
	[`WEAPON_CRUTCH`] = { minor = true },
	[`WEAPON_SHOVEL`] = { minor = true },
	[`WEAPON_PISTOL`] = { minor = false, violent = true },
	[`WEAPON_SNSPISTOL`] = { minor = false, violent = true },
	[`WEAPON_SNSPISTOL_MK2`] = { minor = false, violent = true },
	[`WEAPON_COMBATPISTOL`] = { minor = false, violent = true },
	[`WEAPON_APPISTOL`] = { minor = false, violent = true },
	[`WEAPON_PISTOL50`] = { minor = false, violent = true },
	[`WEAPON_MICROSMG`] = { minor = false, violent = true },
	[`WEAPON_MAC10`] = { minor = false, violent = true },
	[`WEAPON_SMG`] = { minor = false, violent = true },
	[`WEAPON_SMG_MK2`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTSMG`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTRIFLE`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTRIFLE_MK2`] = { minor = false, violent = true },
	[`WEAPON_CARBINERIFLE`] = { minor = false, violent = true },
	[`WEAPON_CARBINERIFLE_MK2`] = { minor = false, violent = true },
	[`WEAPON_ADVANCEDRIFLE`] = { minor = false, violent = true },
	[`WEAPON_MG`] = { minor = false, violent = true },
	[`WEAPON_COMBATMG`] = { minor = false, violent = true },
	[`WEAPON_PUMPSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_SAWNOFFSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_BULLPUPSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_STUNGUN`] = { minor = true, violent = true },
	[`WEAPON_TASER`] = { minor = true, violent = true },
	[`WEAPON_SNIPERRIFLE`] = { minor = false, violent = true },
	[`WEAPON_SNIPERRIFLE2`] = { minor = false, violent = true },
	[`WEAPON_HEAVYSNIPER`] = { minor = false, violent = true },
	[`WEAPON_REMOTESNIPER`] = { minor = false, violent = true },
	[`WEAPON_GRENADELAUNCHER`] = { minor = false, violent = true },
	[`WEAPON_GRENADELAUNCHER_SMOKE`] = { minor = true, violent = true },
	[`WEAPON_RPG`] = { minor = false, violent = true },
	[`WEAPON_STINGER`] = { minor = false, violent = true },
	[`WEAPON_MINIGUN`] = { minor = false, violent = true },
	[`WEAPON_GRENADE`] = { minor = false, violent = true },
	[`WEAPON_STICKYBOMB`] = { minor = false, violent = true },
	[`WEAPON_SMOKEGRENADE`] = { minor = false, violent = true },
	[`WEAPON_BZGAS`] = { minor = false, violent = true },
	[`WEAPON_MOLOTOV`] = { minor = false, violent = true },
	[`WEAPON_FIREEXTINGUISHER`] = { minor = true },
	[`WEAPON_PETROLCAN`] = { minor = false },
	[`WEAPON_FLARE`] = { minor = false },
	[`WEAPON_BARBED_WIRE`] = { minor = false },
	[`WEAPON_DROWNING`] = { minor = false },
	[`WEAPON_DROWNING_IN_VEHICLE`] = { minor = false },
	[`WEAPON_BLEEDING`] = { minor = false },
	[`WEAPON_ELECTRIC_FENCE`] = { minor = true },
	[`WEAPON_EXPLOSION`] = { minor = false },
	[`WEAPON_FALL`] = { minor = true },
	[`WEAPON_EXHAUSTION`] = { minor = true },
	[`WEAPON_HIT_BY_WATER_CANNON`] = { minor = false, violent = true },
	[`WEAPON_RAMMED_BY_CAR`] = { minor = true },
	[`WEAPON_RUN_OVER_BY_CAR`] = { minor = false },
	[`WEAPON_HELI_CRASH`] = { minor = false },
	[`WEAPON_FIRE`] = { minor = false },
	[`WEAPON_ASSAULTSMG`] = { minor = false, violent = true },
	[`WEAPON_GUSENBERG`] = { minor = false, violent = true },
	[`WEAPON_COMBATPDW`] = { minor = false, violent = true },
	[`WEAPON_HEAVYSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_AUTOSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_BULLPUPSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTSHOTGUN`] = { minor = false, violent = true },
	[`WEAPON_BULLPUPRIFLE`] = { minor = false, violent = true },
	[`WEAPON_BULLPUPRIFLE_MK2`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTRIFLE`] = { minor = false, violent = true },
	[`WEAPON_ASSAULTRIFLE_MK2`] = { minor = false, violent = true },
	[`WEAPON_PISTOL_MK2`] = { minor = false, violent = true },
	[`WEAPON_BEANBAG`] = { minor = true },
	[`WEAPON_AR15`] = { minor = false, violent = true },
	[`WEAPON_50BEOWULF`] = { minor = false, violent = true },
	[`WEAPON_P90FM`] = { minor = false, violent = true },
	[`WEAPON_GLOCK19`] = { minor = false, violent = true },
	[`WEAPON_GLOCK19_CIV`] = { minor = false, violent = true },
	[`WEAPON_FNX`] = { minor = false, violent = true },
	[-1553120962] = { minor = true },
	[`WEAPON_FIVESEVEN`] = { minor = false, violent = true },
	[`WEAPON_M249`] = { minor = false, violent = true },
	[`WEAPON_FM1_HK416`] = { minor = false, violent = true },
	[`WEAPON_FM2_HK416`] = { minor = false, violent = true },
	[`WEAPON_HK417`] = { minor = false, violent = true },
	[`WEAPON_FM1_M9A3`] = { minor = false, violent = true },
	[`WEAPON_FM1_HONEYBADGER`] = { minor = false, violent = true },
	[`WEAPON_AK74_1`] = { minor = false, violent = true },
	[`WEAPON_AK74_2`] = { minor = false, violent = true },
	[`WEAPON_ASVAL`] = { minor = false, violent = true },
	[`WEAPON_BENELLIM2`] = { minor = false, violent = true },
	[`WEAPON_BENELLIM2_PD`] = { minor = false, violent = true },
	[`WEAPON_DOUBLEBARRELFM`] = { minor = false, violent = true },
	[`WEAPON_MCXRATTLER`] = { minor = false, violent = true },
	[`WEAPON_MCXSPEAR`] = { minor = false, violent = true },
	[`WEAPON_MK14`] = { minor = false, violent = true },
	[`WEAPON_MK47BANSHEE2`] = { minor = false, violent = true },
	[`WEAPON_MK47BANSHEE`] = { minor = false, violent = true },
	[`WEAPON_MK47FM`] = { minor = false, violent = true },
	[`WEAPON_NSR9`] = { minor = false, violent = true },
	[`WEAPON_PM4`] = { minor = false, violent = true },
	[`WEAPON_RFB`] = { minor = false, violent = true },
	[`WEAPON_VECTOR`] = { minor = false, violent = true },
	[`WEAPON_HKUMP`] = { minor = false, violent = true },
	[`WEAPON_HKUMP_PD`] = { minor = false, violent = true },
	
	[`WEAPON_MPX`] = { minor = false, violent = true },
	[`WEAPON_MINIUZI`] = { minor = false, violent = true },
	[`WEAPON_MP9A`] = { minor = false, violent = true },
	[`WEAPON_L5`] = { minor = false, violent = true },
	[`WEAPON_FIVESEVEN_PD`] = { minor = false, violent = true },
	[`WEAPON_FM1_P226_PD`] = { minor = false, violent = true },
	[`WEAPON_2011_PD`] = { minor = false, violent = true },
	[`WEAPON_2011`] = { minor = false, violent = true },
	[`WEAPON_AK47`] = { minor = false, violent = true },
	[`WEAPON_SA80`] = { minor = false, violent = true },
	[`WEAPON_38SNUBNOSE`] = { minor = false, violent = true },
	[`WEAPON_38SNUBNOSE2`] = { minor = false, violent = true },
	[`WEAPON_38SNUBNOSE2`] = { minor = false, violent = true },
	[`WEAPON_38SPECIAL`] = { minor = false, violent = true },
	[`WEAPON_44MAGNUM`] = { minor = false, violent = true },
	[`WEAPON_44MAGNUM_PD`] = { minor = false, violent = true },
	[`WEAPON_FM1_CZ75`] = { minor = false, violent = true },
	[`WEAPON_FN509`] = { minor = false, violent = true },
	[`WEAPON_SWMP9`] = { minor = false, violent = true },
	[`WEAPON_FM1_P226`] = { minor = false, violent = true },
	[`WEAPON_MP5`] = { minor = false, violent = true },
	[`WEAPON_G36`] = { minor = false, violent = true },
}
